apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: hashicorp
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: vault
      version: '0.31.0'
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 5m
  releaseName: vault
  values:
    resources:
     requests:
       cpu: 50m
       memory: 128Mi
     limits:
       cpu: 100m
       memory: 512Mi
    ui:
      enabled: true