apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: keda
      version: '2.18.2'
      sourceRef:
        kind: HelmRepository
        name: kedacore
      interval: 5m
  releaseName: keda