apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-external-secret
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: flux-vault-store
    kind: SecretStore
  target:
    name: github-receiver-webhook-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: flux
        property: github-webhook-token
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-receiver
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: github-receiver-webhook-token
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: flux-system
      namespace: flux-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: github-receiver-httproute
  namespace: flux-system
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "github-receiver.master.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: webhook-receiver
          port: 80