apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: flux-vault-store
  namespace: flux-system
spec:
  provider:
    vault:
      server: "http://vault.hashicorp:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "flux"
          serviceAccountRef:
            name: flux
