apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: team-a
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: external-secret-dbpass
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: db-pass
        property: password
