apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: team-a-vault
  namespace: team-a
spec:
  provider: vault
  parameters:
    usePodServiceAccountToken: "true"
    vaultAddress: "http://vault.hashicorp.svc.cluster.local:8200"
    roleName: "team-a"
    jwtAudience: "https://kubernetes.default.svc.cluster.local"
    objects: |
      - objectName: "team-a"
        objectType: "kv"

  secretObjects:
    - secretName: demo-service-secret
      type: Opaque
      data:
        - objectName: "team-a"
          key: demo-service-password
