apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: team-a-vault-database
  namespace: team-a
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.hashicorp:8200"
    roleName: "team-a"
    objects: |
      - objectName: "db-password"
        secretPath: "kv/data/db-pass"
        secretKey: "password"
      - objectName: "db-password2"
        secretPath: "kv/data/db-pass"
        secretKey: "password2"
  secretObjects:
    - data:
        - key: password
          objectName: db-password
        - key: password2
          objectName: db-password2
      secretName: dbpass
      type: Opaque
