apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: session
  namespace: team-a
spec:
  serviceName: session
  selector:
    matchLabels:
      app: session
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
        - name: session
          image: redis:7.4.2
          args: ["--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru", "--appendonly", "no", "--save 300 10"]
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: session
  namespace: team-a
spec:
  ports:
    - port: 6379
  selector:
    app: session
#---
#apiVersion: gateway.networking.k8s.io/v1alpha2
#kind: TCPRoute
#metadata:
#  name: session-route
#  namespace: team-a
#spec:
#  parentRefs:
#    - name: traefik-gateway
#      namespace: traefik
#      sectionName: team-a-session
#  rules:
#    - backendRefs:
#        - name: session
#          port: 6379


