apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mvc-demo
  namespace: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mvc-demo
      component: java
  template:
    metadata:
      labels:
        app: spring-mvc-demo
        component: java
    spec:
      containers:
        - image: "ebinsu/spring-mvc-demo:latest"
          imagePullPolicy: IfNotPresent
          name: spring-mvc-demo
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mvc-demo
  namespace: team-a
spec:
  ports:
    - port: 8080
  selector:
    app: spring-mvc-demo
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-httproute
  namespace: team-a
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /demo
      backendRefs:
        - name: spring-mvc-demo
          port: 8080
