apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: '1.5.5'
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
      interval: 5m
  releaseName: csi-secrets-store